unit MD3.Main;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, FMX.TabControl,
  FMX.Controls.Presentation, FMX.StdCtrls, FMX.Objects, System.ImageList,
  FMX.ImgList, FMX.Layouts, FMX.Effects, FMX.Filter.Effects, FMX.Memo.Types,
  FMX.Edit, FMX.ScrollBox, FMX.Memo, FMX.Switch.Style, FMX.EditBox, FMX.SpinBox,
  FMX.DateTimeCtrls, FMX.Calendar, FMX.Calendar.Style, FMX.Menus, FMX.ListBox,
  HGM.MaterialDesignStyle, FMX.Colors, FMX.TreeView, System.Rtti, FMX.Grid.Style,
  FMX.Grid, Data.Bind.Components, Data.Bind.ObjectScope, Data.Bind.GenData,
  Fmx.Bind.GenData, Data.Bind.EngExt, Fmx.Bind.DBEngExt, Fmx.Bind.Grid,
  System.Bindings.Outputs, Fmx.Bind.Editors, Data.Bind.Grid, FMX.NumberBox,
  FMX.ExtCtrls, FMX.ComboEdit, FMX.ListView.Types, FMX.ListView.Appearances,
  FMX.ListView.Adapters.Base, FMX.ListView, FMX.ComboTrackBar,
  FMX.MagnifierGlass, FMX.Header, FMX.MultiView, Data.Bind.Controls,
  Fmx.Bind.Navigator;

type
  TFormMain = class(TForm)
    TabControl1: TTabControl;
    TabItemButtons: TTabItem;
    TabItem2: TTabItem;
    StyleBookMD3: TStyleBook;
    ImageList: TImageList;
    ScrollBox1: TScrollBox;
    Panel1: TPanel;
    Button1: TButton;
    Button2: TButton;
    Label1: TLabel;
    Button3: TButton;
    Button4: TButton;
    Button5: TButton;
    Button6: TButton;
    Label2: TLabel;
    Label3: TLabel;
    Button7: TButton;
    Button8: TButton;
    Button9: TButton;
    Label4: TLabel;
    Button10: TButton;
    Button11: TButton;
    Button12: TButton;
    Label5: TLabel;
    Button13: TButton;
    Button14: TButton;
    Button15: TButton;
    Button16: TButton;
    Button17: TButton;
    Button18: TButton;
    Button19: TButton;
    Button20: TButton;
    ImageList24: TImageList;
    Rectangle1: TRectangle;
    ScrollBox2: TScrollBox;
    Panel2: TPanel;
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    CheckBox3: TCheckBox;
    Label8: TLabel;
    Panel3: TPanel;
    RadioButton1: TRadioButton;
    RadioButton2: TRadioButton;
    RadioButton3: TRadioButton;
    Label7: TLabel;
    Panel4: TPanel;
    ProgressBar1: TProgressBar;
    ProgressBar3: TProgressBar;
    ProgressBar5: TProgressBar;
    ProgressBar4: TProgressBar;
    Label6: TLabel;
    ProgressBar2: TProgressBar;
    ProgressBar6: TProgressBar;
    ProgressBar7: TProgressBar;
    ProgressBar8: TProgressBar;
    ProgressBar9: TProgressBar;
    Panel6: TPanel;
    Label9: TLabel;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    CheckBox9: TCheckBox;
    Panel7: TPanel;
    TrackBar1: TTrackBar;
    Label10: TLabel;
    TrackBar2: TTrackBar;
    TabItem1: TTabItem;
    ScrollBox3: TScrollBox;
    TabItem3: TTabItem;
    Panel5: TPanel;
    Label15: TLabel;
    TimeEdit1: TTimeEdit;
    DateEdit1: TDateEdit;
    Calendar1: TCalendar;
    PopupMenu1: TPopupMenu;
    MenuItem1: TMenuItem;
    MenuItem2: TMenuItem;
    MenuItem3: TMenuItem;
    MenuItem4: TMenuItem;
    MenuItem5: TMenuItem;
    MenuItem6: TMenuItem;
    MenuItem7: TMenuItem;
    MenuItem8: TMenuItem;
    MenuItem9: TMenuItem;
    MenuItem10: TMenuItem;
    MenuItem11: TMenuItem;
    MenuItem12: TMenuItem;
    MenuItem13: TMenuItem;
    MenuItem14: TMenuItem;
    MenuItem15: TMenuItem;
    MenuItem16: TMenuItem;
    MenuItem17: TMenuItem;
    MenuItem18: TMenuItem;
    MenuItem19: TMenuItem;
    MenuItem20: TMenuItem;
    MenuItem21: TMenuItem;
    MenuItem22: TMenuItem;
    TabItem4: TTabItem;
    ScrollBox4: TScrollBox;
    ScrollBox5: TScrollBox;
    Rectangle2: TRectangle;
    ListBox1: TListBox;
    ListBoxItem1: TListBoxItem;
    ListBoxItem2: TListBoxItem;
    ListBoxItem3: TListBoxItem;
    Label16: TLabel;
    ListBoxItem4: TListBoxItem;
    ListBoxItem5: TListBoxItem;
    ListBoxItem6: TListBoxItem;
    ListBoxItem7: TListBoxItem;
    ListBoxItem8: TListBoxItem;
    ListBoxItem9: TListBoxItem;
    ListBoxItem10: TListBoxItem;
    ListBoxItem11: TListBoxItem;
    ListBoxItem12: TListBoxItem;
    ListBoxItem13: TListBoxItem;
    ListBoxItem14: TListBoxItem;
    ListBox2: TListBox;
    ListBoxItem15: TListBoxItem;
    ListBoxItem16: TListBoxItem;
    ListBoxItem17: TListBoxItem;
    ListBoxItem18: TListBoxItem;
    ListBoxItem19: TListBoxItem;
    ListBoxItem20: TListBoxItem;
    ListBoxItem21: TListBoxItem;
    ListBoxItem22: TListBoxItem;
    ListBoxItem23: TListBoxItem;
    ListBoxItem24: TListBoxItem;
    ListBoxItem25: TListBoxItem;
    ListBoxItem26: TListBoxItem;
    ListBoxItem27: TListBoxItem;
    ListBoxItem28: TListBoxItem;
    ListBox3: TListBox;
    ListBoxItem29: TListBoxItem;
    ListBoxItem30: TListBoxItem;
    ListBoxItem31: TListBoxItem;
    ListBoxItem32: TListBoxItem;
    ListBoxItem33: TListBoxItem;
    ListBoxItem34: TListBoxItem;
    ListBoxItem35: TListBoxItem;
    ListBoxItem36: TListBoxItem;
    ListBoxItem37: TListBoxItem;
    ListBoxItem38: TListBoxItem;
    ListBoxItem39: TListBoxItem;
    ListBoxItem40: TListBoxItem;
    ListBoxItem41: TListBoxItem;
    ListBoxItem42: TListBoxItem;
    ListBox4: TListBox;
    ListBoxItem43: TListBoxItem;
    ListBoxItem44: TListBoxItem;
    ListBoxItem45: TListBoxItem;
    ListBoxItem46: TListBoxItem;
    ListBoxItem47: TListBoxItem;
    ListBoxItem48: TListBoxItem;
    ListBoxItem49: TListBoxItem;
    ListBoxItem50: TListBoxItem;
    ListBoxItem51: TListBoxItem;
    ListBoxItem52: TListBoxItem;
    ListBoxItem53: TListBoxItem;
    ListBoxItem54: TListBoxItem;
    ListBoxItem55: TListBoxItem;
    ListBoxItem56: TListBoxItem;
    ListBox5: TListBox;
    ListBoxItem57: TListBoxItem;
    ListBoxItem58: TListBoxItem;
    ListBoxItem59: TListBoxItem;
    ListBoxItem60: TListBoxItem;
    ListBoxItem61: TListBoxItem;
    ListBoxItem62: TListBoxItem;
    ListBoxItem63: TListBoxItem;
    ListBoxItem64: TListBoxItem;
    ListBoxItem65: TListBoxItem;
    ListBoxItem66: TListBoxItem;
    ListBoxItem67: TListBoxItem;
    ListBoxItem68: TListBoxItem;
    ListBoxItem69: TListBoxItem;
    ListBoxItem70: TListBoxItem;
    ListBox6: TListBox;
    ListBoxItem71: TListBoxItem;
    ListBoxItem72: TListBoxItem;
    ListBoxItem73: TListBoxItem;
    ListBoxItem74: TListBoxItem;
    ListBoxItem75: TListBoxItem;
    ListBoxItem76: TListBoxItem;
    ListBoxItem77: TListBoxItem;
    ListBoxItem78: TListBoxItem;
    ListBoxItem79: TListBoxItem;
    ListBoxItem80: TListBoxItem;
    ListBoxItem81: TListBoxItem;
    ListBoxItem82: TListBoxItem;
    ListBoxItem83: TListBoxItem;
    ListBoxItem84: TListBoxItem;
    TrackBar4: TTrackBar;
    TrackBar5: TTrackBar;
    Panel9: TPanel;
    Memo1: TMemo;
    Label17: TLabel;
    ColorPanelPrimary: TColorPanel;
    ColorPanelOnPrimary: TColorPanel;
    ColorPanelSeconadry: TColorPanel;
    Button21: TButton;
    Button22: TButton;
    Button23: TButton;
    Panel10: TPanel;
    ComboColorBox1: TComboColorBox;
    Label18: TLabel;
    ComboColorBox2: TComboColorBox;
    Label19: TLabel;
    ComboBox1: TComboBox;
    ComboBox2: TComboBox;
    Label20: TLabel;
    ColorPanelSurface: TColorPanel;
    TreeView1: TTreeView;
    TreeViewItem1: TTreeViewItem;
    TreeViewItem2: TTreeViewItem;
    TreeViewItem6: TTreeViewItem;
    TreeViewItem7: TTreeViewItem;
    TreeViewItem12: TTreeViewItem;
    TreeViewItem13: TTreeViewItem;
    TreeViewItem8: TTreeViewItem;
    TreeViewItem9: TTreeViewItem;
    TreeViewItem3: TTreeViewItem;
    TreeViewItem10: TTreeViewItem;
    TreeViewItem11: TTreeViewItem;
    TreeViewItem4: TTreeViewItem;
    TreeViewItem5: TTreeViewItem;
    ColorPanelOnSecSurf: TColorPanel;
    Panel8: TPanel;
    Label11: TLabel;
    Edit2: TEdit;
    Label12: TLabel;
    Edit3: TEdit;
    ClearEditButton1: TClearEditButton;
    PasswordEditButton1: TPasswordEditButton;
    SearchEditButton1: TSearchEditButton;
    EllipsesEditButton1: TEllipsesEditButton;
    DropDownEditButton1: TDropDownEditButton;
    SpinEditButton1: TSpinEditButton;
    Label13: TLabel;
    Edit4: TEdit;
    ClearEditButton2: TClearEditButton;
    Label14: TLabel;
    Edit1: TEdit;
    Edit5: TEdit;
    ClearEditButton3: TClearEditButton;
    PasswordEditButton2: TPasswordEditButton;
    SearchEditButton2: TSearchEditButton;
    EllipsesEditButton2: TEllipsesEditButton;
    DropDownEditButton2: TDropDownEditButton;
    SpinEditButton2: TSpinEditButton;
    Edit6: TEdit;
    ClearEditButton4: TClearEditButton;
    Memo2: TMemo;
    EditButton1: TEditButton;
    ListBox7: TListBox;
    ListBoxItem85: TListBoxItem;
    ListBoxItem86: TListBoxItem;
    ListBoxItem87: TListBoxItem;
    ListBoxItem88: TListBoxItem;
    ListBoxItem89: TListBoxItem;
    ListBoxItem90: TListBoxItem;
    ListBoxItem91: TListBoxItem;
    ListBoxItem92: TListBoxItem;
    ListBoxItem93: TListBoxItem;
    ListBoxItem94: TListBoxItem;
    ListBoxItem95: TListBoxItem;
    ListBoxItem96: TListBoxItem;
    ListBoxItem97: TListBoxItem;
    ListBoxItem98: TListBoxItem;
    ListBox8: TListBox;
    ListBoxItem100: TListBoxItem;
    ListBoxItem101: TListBoxItem;
    ListBoxItem102: TListBoxItem;
    ListBoxItem103: TListBoxItem;
    ListBoxItem104: TListBoxItem;
    ListBoxItem105: TListBoxItem;
    ListBoxItem106: TListBoxItem;
    ListBoxItem107: TListBoxItem;
    ListBoxItem108: TListBoxItem;
    ListBoxItem109: TListBoxItem;
    ListBoxItem110: TListBoxItem;
    ListBoxItem111: TListBoxItem;
    ListBoxItem112: TListBoxItem;
    TabItem5: TTabItem;
    ScrollBox6: TScrollBox;
    Panel11: TPanel;
    Label21: TLabel;
    CornerButton1: TCornerButton;
    CornerButton2: TCornerButton;
    CornerButton3: TCornerButton;
    CornerButton4: TCornerButton;
    CornerButton5: TCornerButton;
    CornerButton6: TCornerButton;
    Edit7: TEdit;
    TabItem6: TTabItem;
    Layout1: TLayout;
    Rectangle3: TRectangle;
    Rectangle4: TRectangle;
    Splitter1: TSplitter;
    Splitter2: TSplitter;
    Splitter3: TSplitter;
    Rectangle6: TRectangle;
    Rectangle5: TRectangle;
    Rectangle7: TRectangle;
    Splitter4: TSplitter;
    TabItem7: TTabItem;
    TabItem8: TTabItem;
    StringGrid1: TStringGrid;
    PrototypeBindSource1: TPrototypeBindSource;
    BindingsList1: TBindingsList;
    LinkGridToDataSourcePrototypeBindSource12: TLinkGridToDataSource;
    TabItem9: TTabItem;
    AniIndicator1: TAniIndicator;
    AniIndicator2: TAniIndicator;
    AniIndicator3: TAniIndicator;
    AniIndicator4: TAniIndicator;
    Button29: TButton;
    EditButton2: TEditButton;
    TabItem10: TTabItem;
    ArcDial1: TArcDial;
    ArcDial2: TArcDial;
    CalloutPanel1: TCalloutPanel;
    SpinBox1: TSpinBox;
    ToolBar4: TToolBar;
    Button36: TButton;
    Button39: TButton;
    Button40: TButton;
    Button41: TButton;
    Button42: TButton;
    ToolBar5: TToolBar;
    Button43: TButton;
    Button44: TButton;
    Button45: TButton;
    Button46: TButton;
    Button47: TButton;
    TabControl2: TTabControl;
    TabItem11: TTabItem;
    TabItem12: TTabItem;
    Layout2: TLayout;
    ToolBar1: TToolBar;
    Button24: TButton;
    Button25: TButton;
    Button26: TButton;
    Button27: TButton;
    Button28: TButton;
    VertScrollBox1: TVertScrollBox;
    Layout3: TLayout;
    ToolBar2: TToolBar;
    Button31: TButton;
    Button32: TButton;
    Button33: TButton;
    Button34: TButton;
    Button35: TButton;
    VertScrollBox2: TVertScrollBox;
    ToolBar3: TToolBar;
    Button37: TButton;
    Button38: TButton;
    Label22: TLabel;
    Layout4: TLayout;
    TabItem13: TTabItem;
    Layout5: TLayout;
    ToolBar6: TToolBar;
    Button48: TButton;
    Button49: TButton;
    Button50: TButton;
    Button51: TButton;
    Button52: TButton;
    VertScrollBox3: TVertScrollBox;
    Layout6: TLayout;
    Edit9: TEdit;
    SearchEditButton4: TSearchEditButton;
    EditButton4: TEditButton;
    Button53: TButton;
    Button30: TButton;
    Button54: TButton;
    Button55: TButton;
    Circle2: TCircle;
    Label23: TLabel;
    Label24: TLabel;
    StatusBar1: TStatusBar;
    NumberBox1: TNumberBox;
    PopupBox1: TPopupBox;
    ComboEdit2: TComboEdit;
    Label26: TLabel;
    Label27: TLabel;
    ComboEdit3: TComboEdit;
    Label28: TLabel;
    ColorButton1: TColorButton;
    ColorPanel1: TColorPanel;
    ColorListBox2: TColorListBox;
    ColorButton2: TColorButton;
    ImageControl1: TImageControl;
    Expander1: TExpander;
    TabItem14: TTabItem;
    ListView1: TListView;
    LinkListControlToField1: TLinkListControlToField;
    SpeedButton1: TSpeedButton;
    DropTarget1: TDropTarget;
    DropTarget2: TDropTarget;
    DropTarget3: TDropTarget;
    ComboTrackBar1: TComboTrackBar;
    Label29: TLabel;
    Label30: TLabel;
    ComboTrackBar2: TComboTrackBar;
    MagnifierGlass1: TMagnifierGlass;
    MagnifierGlass2: TMagnifierGlass;
    Header1: THeader;
    HeaderItem1: THeaderItem;
    HeaderItem2: THeaderItem;
    HeaderItem3: THeaderItem;
    HeaderItem4: THeaderItem;
    TabItem15: TTabItem;
    MultiView2: TMultiView;
    Layout7: TLayout;
    Layout8: TLayout;
    Label31: TLabel;
    Button57: TButton;
    Button58: TButton;
    Panel12: TPanel;
    Label32: TLabel;
    Button59: TButton;
    Button60: TButton;
    Button61: TButton;
    Panel13: TPanel;
    Button62: TButton;
    ColorPanelOnSurfCont: TColorPanel;
    Grid1: TGrid;
    LinkGridToDataSourcePrototypeBindSource1: TLinkGridToDataSource;
    Button63: TButton;
    Timer1: TTimer;
    TabControl3: TTabControl;
    TabItem16: TTabItem;
    TabItem17: TTabItem;
    MultiView1: TMultiView;
    Button56: TButton;
    MultiView3: TMultiView;
    Button64: TButton;
    TabItem18: TTabItem;
    MultiView4: TMultiView;
    TabItem19: TTabItem;
    MultiView5: TMultiView;
    TabItem20: TTabItem;
    MultiView6: TMultiView;
    Rectangle8: TRectangle;
    Label33: TLabel;
    Rectangle9: TRectangle;
    Label34: TLabel;
    Rectangle10: TRectangle;
    Label35: TLabel;
    Rectangle11: TRectangle;
    Label36: TLabel;
    Rectangle12: TRectangle;
    Label37: TLabel;
    Button68: TButton;
    Button69: TButton;
    Button65: TButton;
    Button66: TButton;
    Button70: TButton;
    Button71: TButton;
    Button72: TButton;
    Button73: TButton;
    Button74: TButton;
    Label38: TLabel;
    Panel14: TPanel;
    Panel15: TPanel;
    Button75: TButton;
    Button76: TButton;
    Button77: TButton;
    Button78: TButton;
    Button79: TButton;
    Button80: TButton;
    Label40: TLabel;
    Panel16: TPanel;
    Panel17: TPanel;
    Button81: TButton;
    Button82: TButton;
    Button83: TButton;
    Button84: TButton;
    Button85: TButton;
    Button86: TButton;
    Label42: TLabel;
    Layout11: TLayout;
    Label43: TLabel;
    Panel18: TPanel;
    Panel19: TPanel;
    Button87: TButton;
    Button88: TButton;
    Button89: TButton;
    Button90: TButton;
    Button91: TButton;
    Button92: TButton;
    Label44: TLabel;
    Layout12: TLayout;
    Label45: TLabel;
    Panel20: TPanel;
    Panel21: TPanel;
    Button93: TButton;
    Button94: TButton;
    Button95: TButton;
    Button96: TButton;
    Button97: TButton;
    Button98: TButton;
    Label46: TLabel;
    Layout13: TLayout;
    Label47: TLabel;
    Panel22: TPanel;
    Panel23: TPanel;
    Button99: TButton;
    Label48: TLabel;
    Label49: TLabel;
    Label25: TLabel;
    Label50: TLabel;
    Label51: TLabel;
    Label52: TLabel;
    Label53: TLabel;
    Label54: TLabel;
    GroupBox1: TGroupBox;
    Label55: TLabel;
    Label56: TLabel;
    Label57: TLabel;
    Button100: TButton;
    Button101: TButton;
    Button102: TButton;
    Button103: TButton;
    Button104: TButton;
    Button105: TButton;
    Button106: TButton;
    Button107: TButton;
    Button108: TButton;
    Button109: TButton;
    Button110: TButton;
    Button111: TButton;
    Button112: TButton;
    Button113: TButton;
    Button118: TButton;
    Button119: TButton;
    BindNavigator1: TBindNavigator;
    Label58: TLabel;
    BindNavigator2: TBindNavigator;
    Button120: TButton;
    Button121: TButton;
    Button122: TButton;
    Button123: TButton;
    Button124: TButton;
    Button125: TButton;
    Button126: TButton;
    Button127: TButton;
    Button128: TButton;
    Button129: TButton;
    Button130: TButton;
    Button114: TButton;
    Button115: TButton;
    Button116: TButton;
    Button117: TButton;
    Button131: TButton;
    Button132: TButton;
    Button133: TButton;
    Button134: TButton;
    Button135: TButton;
    Button136: TButton;
    Button137: TButton;
    Button138: TButton;
    Button139: TButton;
    Button140: TButton;
    Button141: TButton;
    Button142: TButton;
    Button143: TButton;
    Button144: TButton;
    Button145: TButton;
    Button146: TButton;
    Button147: TButton;
    Button148: TButton;
    Button149: TButton;
    Button150: TButton;
    Button151: TButton;
    Button152: TButton;
    Button153: TButton;
    Button154: TButton;
    Button155: TButton;
    Button156: TButton;
    Button157: TButton;
    Button158: TButton;
    Button159: TButton;
    Button160: TButton;
    Layout9: TLayout;
    MultiView7: TMultiView;
    Layout10: TLayout;
    Label39: TLabel;
    Button67: TButton;
    Button161: TButton;
    Panel24: TPanel;
    Label41: TLabel;
    Button162: TButton;
    Button163: TButton;
    Button164: TButton;
    Panel25: TPanel;
    Button165: TButton;
    ListBox9: TListBox;
    ListBoxItem99: TListBoxItem;
    ListBoxItem113: TListBoxItem;
    ListBoxItem114: TListBoxItem;
    ListBoxItem115: TListBoxItem;
    ListBoxItem116: TListBoxItem;
    Layout14: TLayout;
    TabControl4: TTabControl;
    TabItem21: TTabItem;
    TabItem22: TTabItem;
    TabItem23: TTabItem;
    TabItem24: TTabItem;
    Panel26: TPanel;
    Button166: TButton;
    Button167: TButton;
    Label59: TLabel;
    Button168: TButton;
    Button169: TButton;
    Button170: TButton;
    Button171: TButton;
    Label60: TLabel;
    Label61: TLabel;
    Button172: TButton;
    Button173: TButton;
    Button174: TButton;
    Label62: TLabel;
    Button175: TButton;
    Button176: TButton;
    Button177: TButton;
    Label63: TLabel;
    Button178: TButton;
    Button179: TButton;
    Button180: TButton;
    Button181: TButton;
    Button182: TButton;
    Button183: TButton;
    Button184: TButton;
    Button185: TButton;
    VertScrollBox4: TVertScrollBox;
    Panel27: TPanel;
    CheckBox10: TCheckBox;
    CheckBox11: TCheckBox;
    CheckBox12: TCheckBox;
    Label64: TLabel;
    Panel28: TPanel;
    RadioButton4: TRadioButton;
    RadioButton5: TRadioButton;
    RadioButton6: TRadioButton;
    Label65: TLabel;
    Panel29: TPanel;
    Label66: TLabel;
    CheckBox13: TCheckBox;
    CheckBox14: TCheckBox;
    CheckBox15: TCheckBox;
    CheckBox16: TCheckBox;
    CheckBox17: TCheckBox;
    CheckBox18: TCheckBox;
    Panel30: TPanel;
    TrackBar3: TTrackBar;
    Label67: TLabel;
    TrackBar6: TTrackBar;
    TrackBar7: TTrackBar;
    TrackBar8: TTrackBar;
    Panel31: TPanel;
    ProgressBar10: TProgressBar;
    ProgressBar11: TProgressBar;
    ProgressBar12: TProgressBar;
    ProgressBar13: TProgressBar;
    Label68: TLabel;
    ProgressBar14: TProgressBar;
    ProgressBar15: TProgressBar;
    ProgressBar16: TProgressBar;
    ProgressBar17: TProgressBar;
    ProgressBar18: TProgressBar;
    Panel32: TPanel;
    ComboColorBox3: TComboColorBox;
    Label69: TLabel;
    ComboColorBox4: TComboColorBox;
    Label70: TLabel;
    ComboBox3: TComboBox;
    Label71: TLabel;
    ComboBox4: TComboBox;
    ComboEdit1: TComboEdit;
    Label72: TLabel;
    Label73: TLabel;
    ComboEdit4: TComboEdit;
    Label74: TLabel;
    ComboTrackBar3: TComboTrackBar;
    Label75: TLabel;
    Label76: TLabel;
    ComboTrackBar4: TComboTrackBar;
    Panel33: TPanel;
    Label77: TLabel;
    Edit8: TEdit;
    Label78: TLabel;
    Edit10: TEdit;
    PasswordEditButton3: TPasswordEditButton;
    EllipsesEditButton3: TEllipsesEditButton;
    SpinEditButton3: TSpinEditButton;
    EditButton3: TEditButton;
    Label79: TLabel;
    Edit11: TEdit;
    ClearEditButton6: TClearEditButton;
    Label80: TLabel;
    Edit12: TEdit;
    EditButton5: TEditButton;
    Edit13: TEdit;
    ClearEditButton7: TClearEditButton;
    SearchEditButton5: TSearchEditButton;
    DropDownEditButton4: TDropDownEditButton;
    Edit14: TEdit;
    ClearEditButton8: TClearEditButton;
    Edit15: TEdit;
    VertScrollBox5: TVertScrollBox;
    Panel34: TPanel;
    Memo3: TMemo;
    Label81: TLabel;
    Memo4: TMemo;
    Panel35: TPanel;
    Label82: TLabel;
    TimeEdit2: TTimeEdit;
    DateEdit2: TDateEdit;
    Calendar2: TCalendar;
    VertScrollBox6: TVertScrollBox;
    TabItem25: TTabItem;
    TabItem26: TTabItem;
    VertScrollBox8: TVertScrollBox;
    Panel36: TPanel;
    Label83: TLabel;
    ListBox10: TListBox;
    ListBoxItem117: TListBoxItem;
    ListBoxItem118: TListBoxItem;
    ListBoxItem119: TListBoxItem;
    ListBoxItem120: TListBoxItem;
    ListBoxItem121: TListBoxItem;
    ListBoxItem122: TListBoxItem;
    ListBoxItem123: TListBoxItem;
    ListBoxItem124: TListBoxItem;
    ListBoxItem125: TListBoxItem;
    ListBoxItem126: TListBoxItem;
    ListBoxItem127: TListBoxItem;
    ListBoxItem128: TListBoxItem;
    ListBoxItem129: TListBoxItem;
    ListBoxItem130: TListBoxItem;
    ListBox11: TListBox;
    ListBoxItem131: TListBoxItem;
    ListBoxItem132: TListBoxItem;
    ListBoxItem133: TListBoxItem;
    ListBoxItem134: TListBoxItem;
    ListBoxItem135: TListBoxItem;
    ListBoxItem136: TListBoxItem;
    ListBoxItem137: TListBoxItem;
    ListBoxItem138: TListBoxItem;
    ListBoxItem139: TListBoxItem;
    ListBoxItem140: TListBoxItem;
    ListBoxItem141: TListBoxItem;
    ListBoxItem142: TListBoxItem;
    ListBoxItem143: TListBoxItem;
    ListBoxItem144: TListBoxItem;
    ListBox12: TListBox;
    ListBoxItem145: TListBoxItem;
    ListBoxItem146: TListBoxItem;
    ListBoxItem147: TListBoxItem;
    ListBoxItem148: TListBoxItem;
    ListBoxItem149: TListBoxItem;
    ListBoxItem150: TListBoxItem;
    ListBoxItem151: TListBoxItem;
    ListBoxItem152: TListBoxItem;
    ListBoxItem153: TListBoxItem;
    ListBoxItem154: TListBoxItem;
    ListBoxItem155: TListBoxItem;
    ListBoxItem156: TListBoxItem;
    ListBoxItem157: TListBoxItem;
    ListBoxItem158: TListBoxItem;
    TabControl5: TTabControl;
    TabItem27: TTabItem;
    Layout15: TLayout;
    ToolBar7: TToolBar;
    Button186: TButton;
    Button187: TButton;
    Button188: TButton;
    Button189: TButton;
    Button190: TButton;
    VertScrollBox7: TVertScrollBox;
    Layout16: TLayout;
    Button191: TButton;
    Button192: TButton;
    Label84: TLabel;
    Button193: TButton;
    Circle1: TCircle;
    Layout17: TLayout;
    MultiView8: TMultiView;
    Layout18: TLayout;
    Label85: TLabel;
    Button194: TButton;
    Button195: TButton;
    Panel37: TPanel;
    Label86: TLabel;
    Button196: TButton;
    Button197: TButton;
    Button198: TButton;
    Panel38: TPanel;
    Button199: TButton;
    ListBox13: TListBox;
    ListBoxItem159: TListBoxItem;
    ListBoxItem160: TListBoxItem;
    ListBoxItem161: TListBoxItem;
    ListBoxItem162: TListBoxItem;
    ListBoxItem163: TListBoxItem;
    TabItem28: TTabItem;
    Layout19: TLayout;
    ToolBar8: TToolBar;
    Button200: TButton;
    Button201: TButton;
    Button202: TButton;
    Button203: TButton;
    Button204: TButton;
    VertScrollBox9: TVertScrollBox;
    ToolBar9: TToolBar;
    Button205: TButton;
    Button206: TButton;
    Label87: TLabel;
    TabItem29: TTabItem;
    Layout20: TLayout;
    ToolBar10: TToolBar;
    Button207: TButton;
    Button208: TButton;
    Button209: TButton;
    Button210: TButton;
    Button211: TButton;
    VertScrollBox10: TVertScrollBox;
    Layout21: TLayout;
    Edit16: TEdit;
    SearchEditButton3: TSearchEditButton;
    EditButton6: TEditButton;
    Label88: TLabel;
    Button212: TButton;
    Layout22: TLayout;
    MultiView9: TMultiView;
    Layout23: TLayout;
    Label89: TLabel;
    Button213: TButton;
    Button214: TButton;
    Panel39: TPanel;
    Label90: TLabel;
    Button215: TButton;
    Button216: TButton;
    Button217: TButton;
    Panel40: TPanel;
    Button218: TButton;
    Label91: TLabel;
    PopupBox2: TPopupBox;
    Label92: TLabel;
    ArcDial3: TArcDial;
    ArcDial4: TArcDial;
    Label93: TLabel;
    SpinBox2: TSpinBox;
    Label94: TLabel;
    NumberBox2: TNumberBox;
    DropTarget4: TDropTarget;
    DropTarget5: TDropTarget;
    VertScrollBox11: TVertScrollBox;
    procedure TrackBar2Tracking(Sender: TObject);
    procedure FormCreate(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure Button4Click(Sender: TObject);
    procedure FormDestroy(Sender: TObject);
    procedure Button29Click(Sender: TObject);
    procedure DropTarget1DragOver(Sender: TObject; const Data: TDragObject; const Point: TPointF; var Operation: TDragOperation);
    procedure ColorPanelPrimaryChange(Sender: TObject);
    procedure Button63Click(Sender: TObject);
    procedure Timer1Timer(Sender: TObject);
    procedure CheckBox1Click(Sender: TObject);
    procedure CheckBox1Change(Sender: TObject);
  private
    FMDStyle3: TMaterialDesignStyle3;
  public
    { Public declarations }
  end;

var
  FormMain: TFormMain;

implementation

uses
  System.UIConsts, System.Character;

{$R *.fmx}

procedure TFormMain.Button29Click(Sender: TObject);
begin
  AniIndicator4.Visible := False;
  AniIndicator4.Visible := True;
end;

procedure TFormMain.Button2Click(Sender: TObject);
begin
  var Style := TMaterialDesignStyle3.DefaultDarkPallete;
  Style.ColorPrimary := ColorPanelPrimary.Color;
  Style.ColorOnPrimary := ColorPanelOnPrimary.Color;
  Style.ColorSecondaryContainer := ColorPanelSeconadry.Color;
  Style.ColorSurface := ColorPanelSurface.Color;
  Style.ColorOnSecondaryContainer := ColorPanelOnSecSurf.Color;
  Style.ColorSurfaceContainer := ColorPanelOnSurfCont.Color;

  Style.ColorPrimary008 := GetColorWithAlpha(Style.ColorPrimary, 8);
  Style.ColorPrimary012 := GetColorWithAlpha(Style.ColorPrimary, 12);
  Style.ColorOnSurface008 := GetColorWithAlpha(Style.ColorOnSurface, 12);
  Style.ColorOnSurfaceVariant008 := GetColorWithAlpha(Style.ColorOnSurfaceVariant, 8);
  Style.ColorOnSurfaceVariant012 := GetColorWithAlpha(Style.ColorOnSurfaceVariant, 12);
  Style.ColorOnSecondaryContainer008 := GetColorWithAlpha(Style.ColorOnSecondaryContainer, 8);
  Style.ColorSecondaryContainer000 := GetColorWithAlpha(Style.ColorSecondaryContainer, 0);

  Style.ColorSurfaceContainerLow := ColorDarker(Style.ColorSurfaceContainer, 5);
  Style.ColorSurfaceContainerHigh := ColorLighter(Style.ColorSurfaceContainer, 5);
  Style.ColorSurfaceContainerHighest := ColorLighter(Style.ColorSurfaceContainer, 10);

  FMDStyle3.ApplyStyle(Style);

  Rectangle1.Fill.Color := StringToAlphaColor('#FF141218');
  Rectangle2.Fill.Color := StringToAlphaColor('#FF2B2930');
end;

procedure TFormMain.Button4Click(Sender: TObject);
begin
  var Style := TMaterialDesignStyle3.DefaultLightPallete;
  Style.ColorPrimary := ColorPanelPrimary.Color;
  Style.ColorOnPrimary := ColorPanelOnPrimary.Color;
  Style.ColorSecondaryContainer := ColorPanelSeconadry.Color;
  Style.ColorSurface := ColorPanelSurface.Color;
  Style.ColorOnSecondaryContainer := ColorPanelOnSecSurf.Color;
  Style.ColorSurfaceContainer := ColorPanelOnSurfCont.Color;

  Style.ColorPrimary008 := GetColorWithAlpha(Style.ColorPrimary, 8);
  Style.ColorPrimary012 := GetColorWithAlpha(Style.ColorPrimary, 12);
  Style.ColorOnSurface008 := GetColorWithAlpha(Style.ColorOnSurface, 12);
  Style.ColorOnSurfaceVariant008 := GetColorWithAlpha(Style.ColorOnSurfaceVariant, 8);
  Style.ColorOnSurfaceVariant012 := GetColorWithAlpha(Style.ColorOnSurfaceVariant, 12);
  Style.ColorOnSecondaryContainer008 := GetColorWithAlpha(Style.ColorOnSecondaryContainer, 8);
  Style.ColorSecondaryContainer000 := GetColorWithAlpha(Style.ColorSecondaryContainer, 0);

  Style.ColorSurfaceContainerLow := ColorLighter(Style.ColorSurfaceContainer, 5);
  Style.ColorSurfaceContainerHigh := ColorDarker(Style.ColorSurfaceContainer, 5);
  Style.ColorSurfaceContainerHighest := ColorDarker(Style.ColorSurfaceContainer, 10);

  FMDStyle3.ApplyStyle(Style);

  Rectangle1.Fill.Color := StringToAlphaColor('#FFFFFFFF');
  Rectangle2.Fill.Color := StringToAlphaColor('#FFECE6F0');
end;

procedure TFormMain.Button63Click(Sender: TObject);
begin
  Timer1.Enabled := not Timer1.Enabled;
  Grid1.StylesData['progress.Visible'] := Timer1.Enabled;
end;

procedure TFormMain.CheckBox1Change(Sender: TObject);
begin
  ShowMessage('change')
end;

procedure TFormMain.CheckBox1Click(Sender: TObject);
begin
  ShowMessage('click')
end;

procedure TFormMain.ColorPanelPrimaryChange(Sender: TObject);
begin
  //Button4Click(nil);
end;

procedure TFormMain.DropTarget1DragOver(Sender: TObject; const Data: TDragObject; const Point: TPointF; var Operation: TDragOperation);
begin
  Operation := TDragOperation.Copy;
end;

procedure TFormMain.FormCreate(Sender: TObject);
begin
  Button57.StylesData['detail'] := '104';
  Button57.StylesData['detail.Visible'] := True;
  Button58.StylesData['detail'] := '20+';
  Button58.StylesData['detail.Visible'] := True;
  Button60.StylesData['detail'] := '1';
  Button60.StylesData['detail.Visible'] := True;
  FMDStyle3 := TMaterialDesignStyle3.Create(StyleBookMD3);
  ProgressBar2.StylesData['indicator.EndAngle'] := 360 * (ProgressBar2.Value / 100);
  ProgressBar6.StylesData['indicator.EndAngle'] := 360 * (ProgressBar6.Value / 100);
  ProgressBar7.StylesData['indicator.EndAngle'] := 360 * (ProgressBar7.Value / 100);
  ProgressBar8.StylesData['indicator.EndAngle'] := 360 * (ProgressBar8.Value / 100);
  ProgressBar9.StylesData['indicator.EndAngle'] := 360 * (ProgressBar9.Value / 100);
end;

procedure TFormMain.FormDestroy(Sender: TObject);
begin
  FMDStyle3.Free;
end;

procedure TFormMain.Timer1Timer(Sender: TObject);
begin
  Grid1.StylesData['progress.Value'] := Random(100);
end;

procedure TFormMain.TrackBar2Tracking(Sender: TObject);
begin
  TTrackBar(Sender).Thumb.StylesData['hhint.Text'] := Round(TTrackBar(Sender).Value).ToString;
end;

end.

